version: '3'

services:
 postgres:
  image: postgres
  restart: always
  volumes:
   - pgdata:/var/lib/postgresql/data/
  environment:
   - POSTGRES_PASSWORD="pwd"
  ports:
   - "5432:5432"
volumes:
   pgdata: {}